### ISSUE TITLE
Open database locked using keyfile AND password

### ISSUE THREAD

**Issue by andrey-akhmatkhanov** [nongiach/QuicKeepass#2]
The current version allows to unlock database using keyfile OR password. This logic is written in lines 183-187 of the code. But some people (me, for example :)) use both to unlock the database. It might be a good idea to handle somehow this case. Maybe add additional argument like "--require-password"?

**Comment by nongiach** [comment]
Hello Andrey,

sorry for the delay.
This case is documented in the README.md doc:
```sh
quickeepass REPLACE_WITH_YOUR_KEEPASS.kdbx --keyfile your.key --password
```
Indeed the code logic that you point out implicitly handle this case.

Have a nice day.
